"""add_unit_cost_to_general_items

Revision ID: b1800ff2399a
Revises: consolidate_employees
Create Date: 2026-01-11 21:18:33.636475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1800ff2399a'
down_revision: Union[str, Sequence[str], None] = 'consolidate_employees'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'serial_no',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'fss_no',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'first_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_employees_cnic'), 'employees', ['cnic'], unique=False)
    op.add_column('general_items', sa.Column('unit_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general_items', 'unit_cost')
    op.drop_index(op.f('ix_employees_cnic'), table_name='employees')
    op.alter_column('employees', 'last_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('employees', 'fss_no',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'serial_no',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
